### PR TITLE
filtered.csv is not generated anymore. Topic filter fixed as well. 

### PR DESCRIPTION
**Pull request by zarbod**
Fixes Issue #42. filtered.csv is no longer generated and a row list is used instead. genOut.py modified accordingly.

### CODE REVIEW

**Comment by zarbod** [comment]
@sanketgarade the topic filter has been fixed and now splits the tags using semicolons into a list. Multiple tags work now. Fixes issue #49

**Comment by sanketgarade** [comment]
I tested and saw many files are having the below line as the first line in them. Can you check again?

`###### Tags: science;engineering`

**Comment by zarbod** [comment]
Fixed. I was skipping the first line in the csv file by setting the index variable i to 1 instead of 0. Skipping the first line while reading the csv file caused the skipping thing to happen twice. I don't really know why exactly it had that first line, but it's not there anymore.

**Comment by sanketgarade** [comment]
done. thanks for a quick fix!! merged and up on the website 😄

**Comment by zarbod** [comment]
No problem :)

**Pull request merged**
