### PR TITLE
Created a prototype infographics card

### PR DESCRIPTION
**Pull request by gokhaleaaroh**
I have created an html file that generates a card similar to what you have created with keynote. If it is approved, I'll write a python script to automate the generation of such html files.

### CODE REVIEW

**Comment by sanketgarade** [comment]
Can you paste a screenshot of a sample of the created card? (In the comments here)

**Comment by sanketgarade** [comment]
मस्तच! Prototype म्हणून खूप छान केलंय. 😊👍🏼

**Comment by zarbod** [comment]
धन्यवाद. मी आपोआप card बनवण्यासाठी स्क्रिप्ट लिहितो.

**Comment by sanketgarade** [comment]
Thanks! I have merged this, but the script file `card.html` has both CR+LF line endings I think. Not a big issue, but if you can fix in future it'll be great. :)

**Pull request merged**
