### PR TITLE
Updated frontend to work with new backend

### PR DESCRIPTION
**Pull request by the-kaustubh**
- Added search from heroku and db
- Added add word to DB
- TODO: modfying existing word is pending

### CODE REVIEW

**Comment by the-kaustubh** [comment]
@sanketgarade can you please look into this

**Comment by sanketgarade** [comment]
> @sanketgarade can you please look into this

Yes. I'm preoccupied with some work so unable to check right now. Might do in a few days. 

By the way there are merge conflicts. Can you try to resolve those, if possible?

**Comment by sanketgarade** [comment]
- Also please merge into `develop` not into `main`. 
- And the docs folder was supposed to be renamed to search. [Reference here](https://github.com/mukta-strot/mr-shabd-backend/pull/2).

**Comment by sanketgarade** [comment]
@the-kaustubh Please let me know once you have fixed issues mentioned above. After that I will merge. Also cannot merge now as there are conflicts, and I do not know which version of the conflicted code is to be kept.

**Review by sanketgarade — CHANGES_REQUESTED** [review]
conflicts need to be fixed. and other minor changes to be done as mentioned in the comments.

**Comment by sanketgarade** [comment]
@the-kaustubh hey, any idea when you plan to fix this?

**Pull request closed without merging**
