### PR TITLE
Major change in sort function and minor change in syntax checker

### PR DESCRIPTION
**Pull request by zarbod**
Major change in sort function and minor change in syntax checker

### CODE REVIEW

**Comment by zarbod** [comment]
I made the sort function generic, but I don't know how to return a file without creating it locally. For now I'm creating the file in the function. The lists for each column are no longer hard coded into the function.

**Comment by zarbod** [comment]
There is also a minor edit to the syntax checker in this PR. The original code for the syntax checker didn't even work properly and I had to change one line to make it work.

**Comment by sanketgarade** [comment]
Thanks. I'll check this sometime today. 
One request - the scripts have been moved to src folder. Could you update this PR so that the files go to that folder.

**Comment by zarbod** [comment]
Added the scripts to the src folder

**Pull request merged**
