### PR TITLE
Added a way to parse tags

### PR DESCRIPTION
**Pull request by masonwoodford**
Added TopicsParser class. The class's gen_topics function first finds the column index of tags then searches each row at that index and returns the tags in a sorted array.

### CODE REVIEW

**Comment by sanketgarade** [comment]
Thanks 😊. I'm outside right now, so may not to be to review and merge soon. Will try later today. 

By the way did you test this? Also, could you include a **test code** at the bottom of the file in comments (like done in the other files). That'll make it easier for me to test it.

**Comment by masonwoodford** [comment]
Yes after viewing some of the other commits I am actually going to refactor this code a bit as I didn't fully understand the csv reader and I will add some test code.

**Comment by masonwoodford** [comment]
Ok I added a pretty simple test, let me know if you want more. Also as a side note the relative file paths for the csv file were not working for me for some reason so I had to define them as global paths, but for the test paths I went off the assumption that the local paths were working for you, hope that's alright.

**Comment by sanketgarade** [comment]
I tested this. It works fine except for one issue. The output list also includes the "tags" word, which is actually the column name in the header row. So it should ideally be skipped. Could you please fix than? Once that is done, I'll merge the PR. Thanks!!

**Comment by sanketgarade** [comment]
> as a side note the relative file paths for the csv file were not working for me for some reason

Which OS do you use? Windows? Cause that kind of path is not compatible with windows. It works on GNU/Linux based OSs and maybe also on Macs.

**Comment by masonwoodford** [comment]
Yeah I do use Windows ;( Pushed the changes though :)

**Comment by sanketgarade** [comment]
Thanks a lot. 😊

I'll merge this for now but there is one small improvement that can be made later. 

From your latest commit, I saw that you've skipped the rows which has "tags" word in them, but that would mean that if the tags column is renamed from "tags" to something else then this won't work as expected. 

Instead I was actually expecting to skip the "first row", which is basically the header row that holds all the column names. So there is no explicit dependency on the name of the column. 

But anyway this is a minor issue, and I won't rename the tags column to something else keeping this in mind for now.

**Comment by masonwoodford** [comment]
Yeah I thought about that as well, but I figured since I already hard coded the word 'tags' as the search term for the column index I might as well just use it to skip in the parsing. Anyways, thanks for the merging!

**Comment by sanketgarade** [comment]
Understood. No worries. 😊


By the way, are you going to continue with the remaining secondary part that I mentioned in #43 ? (Using your new script in the main.py)

**Comment by masonwoodford** [comment]
Yea sure I can work on that if it is open.

**Comment by sanketgarade** [comment]
Thanks man. 😊 
Please do and send a new PR for it. 

You can try running the current main.py to see what kind of output it gives currently.

Once your integration is done, the running main.py should generate all the topics markdown files, as per the topics parsed by your previous script. 

Just make sure you don't add any of those generated markdown files to the commit.

**Pull request merged**
