### PR TITLE
Created syntax checker assuming that the file will be csv.

### PR DESCRIPTION
**Pull request by zarbod**
Created Syntax Checker

### CODE REVIEW

**Comment by sanketgarade** [comment]
Thanks. Could you please update this to handle/correct the error cases such that 

1. If the commas are lesser than the header row, then append the missing commas. 
2. If the commas are more than the header row, then remove the extra commas. While doing this, also print a warning message mentioning the English word of that row. So that the we can check that row manually to see if the trimming didn't mess up anything else on that row. 

After doing these corrections you can save the new csv with a new name. (Don't include the new corrected csv in the commit.)

**Comment by sanketgarade** [comment]
@zarbod have you already started working on the correction part? if not, i'll merge this for now and you can raise a new PR later for the correction part. if you've already started, i'll wait for this PR to be updated before merging it.

**Comment by zarbod** [comment]
Yeah sorry I haven't gotten the time to start working on the corrections
yet. You can go ahead and merge the current PR. I'll start doing the
correction tonight.

**Comment by sanketgarade** [comment]
No issues at all 😊

**Comment by sanketgarade** [comment]
hey @zarbod , you were working on the corrections mentioned above, I guess. If it is done, you can raise a PR to get it merged. If you haven't started yet, then leave it cause this is anyway not so important and we can live without it. Just let me know whatever is the case, so that I can wait for the PR or close the related issue (#1).

**Comment by zarbod** [comment]
> hey @zarbod , you were working on the corrections mentioned above, I guess. If it is done, you can raise a PR to get it merged. If you haven't started yet, then leave it cause this is anyway not so important and we can live without it. Just let me know whatever is the case, so that I can wait for the PR or close the related issue (#1).

Yeah I don't think I ever got around to implementing those corrections. I'll close the issue.

**Pull request merged**
